### ISSUE TITLE
Update README: Include steps to create local image for fledge client

### ISSUE THREAD

**Issue by dreamer-89** [senthilrch/kube-fledged#10]
Default value for the docker client is:
FLEDGED_DOCKER_CLIENT_IMAGE_NAME=senthilrch/fledged-docker-client:latest

We need to create/update this variable as per developer

**Comment by senthilrch** [comment]
@dreamer-89 : This image is not required now. This will be required only during deletion of images when the imagecache API resource is deleted; this feature is under development. Once developed, README will be updated. Till then use the existing README to build and deploy.
