### ISSUE TITLE
Bug: x509 error re-installing ImageCache

### ISSUE THREAD

**Issue by nadenf** [senthilrch/kube-fledged#113]
* Existing KubeFledged install
* Existing ImageCache
* Helm install (version 0.8.2)

When trying to reinstall the ImageCache I get the following error message:

Internal error occurred: failed calling webhook "validate-image-cache.kubefledged.io": 

Post "https://kube-fledged-webhook-server.system-containers.svc:3443/validate-image-cache?timeout=1s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubefledged.io"

**Comment by senthilrch** [comment]
@nadenf : Thanks for reporting this...This error occurs when kube-api-server calls the validatingwebhookconfiguration endpoint to validate the ImageCache resource and it is unable to verify the certificate of the webhook server..Would like to understand the steps you followed..

Existing KubeFledged install ==> Is it an older version of kube-fledged? Please mention the version and how this was installed (i.e. using yaml/helm/operator)?
Existing ImageCache ==> Pls. share the yaml spec of this existing ImageCache
Helm install (version 0.8.2) ==> OK

==> Please share the yaml spec of the ImageCache you are re-installing
==> Also could you list the validatingwebhookconfiguration resources in the cluster

**Comment by metasim** [comment]
Same problem: 

1. Fresh install from direct manifests (no Helm)
2. Created an `ImageCache`
3. Had an incorrect image tag, so edited yaml
4. Applied the updated `ImageCache`
5. Got this error:

```
Internal error occurred: failed calling webhook "validate-image-cache.kubefledged.io": Post "https://kubefledged-webhook-server.kube-fledged.svc:3443/validate-image-cache?timeout=1s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubefledged.io")
```

**Comment by metasim** [comment]
And here's what's in the webhook log:

```
init I1014 20:56:58.426127       1 init.go:70] success: ca private key created
init I1014 20:56:58.443311       1 init.go:78] success: self-signed ca certificate created
init I1014 20:56:58.443362       1 init.go:86] success: ca certificate encoded to pem format
init I1014 20:57:01.002873       1 init.go:116] success: server private key created
init I1014 20:57:01.018384       1 init.go:124] success: server certificate created
init I1014 20:57:01.018441       1 init.go:132] success: server certificate encoded to pem format
init I1014 20:57:01.018504       1 init.go:139] success: server private key encoded to pem format
init I1014 20:57:01.018607       1 init.go:151] success: server cert (tls.crt) copied to /var/run/secrets/webhook-server/
init I1014 20:57:01.018666       1 init.go:158] success: server key (tls.key) copied to /var/run/secrets/webhook-server/
init I1014 20:57:01.047436       1 init.go:164] success: validatingwebhookconfiguration kubefledged patched
webhook-server I1014 20:57:02.828704       1 server.go:269] Wehook server listening on :443
webhook-server I1014 20:59:59.622752       1 imagecache.go:152] Image cache creation/update validated successfully
webhook-server I1014 21:01:34.505121       1 imagecache.go:152] Image cache creation/update validated successfully
webhook-server 2021/10/14 21:01:34 http: TLS handshake error from 192.168.215.234:47748: remote error: tls: bad certificate
webhook-server 2021/10/14 21:01:34 http: TLS handshake error from 192.168.215.234:47750: remote error: tls: bad certificate
```

**Comment by senthilrch** [comment]
@nadenf @universam1 @metasim : Thanks for reporting this issue. I need to spend time to dig deeper on this issue. Will have this fixed for the upcoming v0.9.0 release.

**Comment by universam1** [comment]
Thanks @senthilrch  for the detailed explanation, hence we are going to remove the webhook as the validation seems to be of a not significant drawback.

AdmissionController per principle are a highly invasive, high trust component in the cluster that could under circumstances lead to unpredictable results.
Because of that we do not like to run them in general if not entirely necessary. Please correct me if I'm wrong, but it looks to me that through some CI linting the validation could be solved as well, for example even simply via a spec validating deployment tool such as `kapp` would do a good part of that too.

Thanks!

**Comment by metasim** [comment]
@senthilrch FYI: I was never able to get the hint [here](https://github.com/senthilrch/kube-fledged/issues/113#issuecomment-953536544) to fully work. Could get things working initially, but then had restart errors when pods got moved around, requiring manual intervention.

**Comment by metasim** [comment]
👏

**Comment by diogouchoas** [comment]
I'm still having this problem with kube-fledged helm chart 0.9.0. Was the problem fixed or the recommended solution is to disable validation hook?

**Comment by senthilrch** [comment]
The previous version v0.8.2 helm chart would create a validatingwebhookconfiguration resource in the namespace. This would get created via helm pre-install hook. When you execute helm delete or perform helm upgrade to v0.9.0, helm won't remove the validatingwebhookconfiguration resource since it was created via pre-install hook. Before installing v0.9.0 helm chart, delete the validatingwebhookconfiguration resource in the namespace.

**Comment by senthilrch** [comment]
I've now added this information to the release note of v0.9.0. Thanks for reporting the issue!!

**Comment by hlhl040** [comment]
Hi, I'm still having this issue with version 0.10.0. It's a fresh install and I'm using the kube-fledged-operator for installation. Seeing this on controller log
> E0714 01:42:45.543060       1 controller.go:216] Error updating ImageCache(kube-fledged-imagecache) status to 'Aborted': Internal error occurred: failed calling webhook "validate-image-cache.kubefledged.io": Post "https://kube-fledged-webhook-server.kube-fledged.svc:3443/validate-image-cache?timeout=1s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubefledged.io")

See this in webhook-server log
> 2023/07/14 01:43:39 http: TLS handshake error from 100.96.2.36:34510: remote error: tls: bad certificate

**Comment by aledeulo** [comment]
Hi there, I'm having the same issue just now, using the v0.10.0 version, any news related? 
I had a fresh installation, it was working fine, then after some updates, and re-installations it started with this issue. I'm using the helm charts to deploy kube-fledged.
Thanks.

**Comment by iTaybb** [comment]
It looks like this happens on upgrades.
Killing the `kube-fledged-webhook-server` pod fixes the issue. At least until the next helm chart upgrade.

It looks like on every helm upgrade, a new set of x509 certificates are being issued for the webhook controller. However the webhook server isn't using the new set of certificates until restarted.

**Comment by winterrobert** [comment]
I get it as well on v0.10.0 and it was blocking ArgoCD from syncing my app with the ImageCache until I manually restarted the webhook server. Worked around it by [disabling the webhookServer](https://github.com/senthilrch/kube-fledged/blob/master/deploy/kubefledged-operator/helm-charts/kubefledged/values.yaml#L11C6-L11C6).

**Comment by jasondamour** [comment]
Why was this issue closed @senthilrch ?

**Comment by yulin-li** [comment]
Same issue. Could the tls be disabled?

**Comment by roeeklinger** [comment]
This still happens and prevents me from using ArgoCD on v0.10.0, downgrading to 0.9.0 seems to solve the issue for me

**Comment by MonolithProjects** [comment]
@roeeklinger to make v0.10.0 work in ArgoCD you can ignore the differences in caBundle in the argocd app manifest spec.
```  
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
```
