### ISSUE TITLE
Add README.md to kube-fledged helm chart

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#136]
It is a good practice to include README.md in helm chart. Add a README.md file to kube-fledged's helm chart located in:
./deploy/kubefledged-operator/helm-charts/kubefledged

The README should have following info:-
- Short description of kube-fledged
kube-fledged is a kubernetes operator for creating and managing a cache of container images directly on the worker nodes of a kubernetes cluster. It allows a user to define a list of images and onto which worker nodes those images should be cached (i.e. pulled). As a result, application pods start almost instantly, since the images need not be pulled from the registry. kube-fledged provides CRUD APIs to manage the lifecycle of the image cache, and supports several configurable parameters to customize the functioning as per one's needs.

- How to install the chart (https://github.com/senthilrch/kube-fledged#quick-install-using-helm-chart)
- Chart parameters (https://github.com/senthilrch/kube-fledged/blob/master/docs/helm-parameters.md)

**Comment by senthilrch** [comment]
SODACODE22: Raise PR against "develop" branch.

**Comment by senthilrch** [comment]
Yes right!

**Comment by anubhav06** [comment]
Great! Can I work on this ?

**Comment by senthilrch** [comment]
Yes
