### ISSUE TITLE
Add Shout-outs section to README

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#139]
Add a section named "Shout-outs" at the end of README. This section would capture links to articles/blogs in which authors mentioned kube-fledged. The section should look like:-

## Shout-outs:
- [Cloud-Native Through the Prism of Percona: Episode 1](https://www.percona.com/blog/cloud-native-series-1)

Add all the below links to the section:
- https://www.percona.com/blog/cloud-native-series-1
- https://collabnix.github.io/kubetools/
- https://itnext.io/kubernetes-essential-tools-2021-def12e84c572
- https://learnk8s.io/kubernetes-autoscaling-strategies
- https://www.libhunt.com/r/kraken
- https://dev.to/ajeetraina/top-200-kubernetes-tools-for-devops-engineer-like-you-3h7e
- https://www.facebook.com/groups/kubernetes.professionals/posts/1055140111994964/
- https://www.reddit.com/r/kubernetes/comments/pxbdkj/kubefledged_cache_container_images_in_kubernetes/

NOTE: Table of contents should be updated using https://github.com/thlorenz/doctoc

**Comment by senthilrch** [comment]
SODACODE2022: Raise PR against 'develop' branch

**Comment by kushal-gopal** [comment]
Hey, would like to work on this.

**Comment by senthilrch** [comment]
Sure. Go for it

**Comment by shelar1423** [comment]
Kindly assign me this issue

**Comment by shelar1423** [comment]
@senthilrch kindly assign me this if @kushal-gopal  is not doing it?

**Comment by senthilrch** [comment]
@shelar1423 assigned it to you

**Comment by kushal-gopal** [comment]
I don't understand the constant annoyance since I was first assigned to this issue. Literally two hours I got assigned to this issue, I was pestered. If someone wanted to work on this issue, I think they should have asked first.
I wanted to go through doctoc before I worked on this issue, within a day, the issue was reassigned. 
Honestly, I don't like this.

**Comment by senthilrch** [comment]
@kushal-gopal Apologies for reassigning it without consulting you. I request you to continue on this and raise PR.

**Comment by shelar1423** [comment]
@kushal-gopal  no worries bro u contribute  💪
@senthilrch  kindly make another issue for me if possible

**Comment by kushal-gopal** [comment]
I am flustered! He has already created a pull request. I think it's best we close this issue.

**Comment by bhuvanessr** [comment]
Please assign to me

**Comment by shelar1423** [comment]
Can u reporn this?
