### ISSUE TITLE
Update Contributing guidelines document

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#144]
https://github.com/senthilrch/kube-fledged/blob/master/CONTRIBUTING.md needs to be updated as follows:-

## We invite contributions to _kube-fledged_. 

- Submit an issue if you find a bug or interested in seeing a new feature/ enhancement implemented.
- If you would like to submit a PR for an existing issue, please make a comment in the issue. The maintainer will review your request and if approved, the issue will be assigned to you.
- Once the issue is assigned to you, start working on the issue.
- Fork the project, develop and test your code.
- Submit a pull request against 'develop' branch. Ensure ALL CI checks are passed.
- The maintainer will review and approve your pull request

**Comment by shelar1423** [comment]
Hey, kindly assign this to me

**Comment by senthilrch** [comment]
Done
