### ISSUE TITLE
Feature: Build multi-arch image with windows support

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#156]
As a first step in supporting windows nodes in kube-fledged, build multi-arch images with windows support. Changes needed in Github action workflow.

**Comment by akhilsahuji** [comment]
Hey 👋 can you elaborate on this issue? I might be able to solve it!

**Comment by senthilrch** [comment]
All images built for kube-fledged are multi-arch images that support linux/amd64, linux/arm, linux/arm64. In order to support windows nodes we'll need to add windows/amd64 as additional architecture to the images. The images are currently built using Github action:-
https://github.com/senthilrch/kube-fledged/blob/develop/.github/workflows/caller.yml

where the target platforms are set as below:-
target_platforms: linux/amd64, linux/arm/v7, linux/arm64/v8

The target_platforms field will be used as input to following task in
https://github.com/senthilrch/kube-fledged/blob/develop/.github/workflows/build-kube-fledged.yml
    - name: Build kubefledged-controller image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.dockerfile_controller }}
        build-args: |
          ALPINE_VERSION=${{ inputs.alpine_version }}
          GOLANG_VERSION=${{ inputs.golang_version }}
        platforms: ${{ inputs.target_platforms }}
        push: ${{ inputs.push_image }}
        tags: ${{ inputs.controller_image_repo }}:${{ inputs.release_version }},${{ inputs.controller_image_repo }}:latest

**Comment by sandeep-v1404** [comment]
Can I work on this issue?

**Comment by senthilrch** [comment]
Yes you can work on this issue

**Comment by slawekww** [comment]
@senthilrch Would you like to share any plans to have kube-fledged supporting Windows images? thx

**Comment by pruthvibs164** [comment]
@senthilrch Can you please share more details on kube-fledged compatibility with Windows node.

1. Can we cache on Windows nodes.
2. If we can't, and need to cache on a Linux node, can the Windows node pull from the cache of a Linux node.

**Comment by senthilrch** [comment]
Duplicate of https://github.com/senthilrch/kube-fledged/issues/118
Hence closing this issue
