### ISSUE TITLE
Update shout-outs section with new links

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#162]
- https://wiki.nikitavoloboev.xyz/operating-systems/containers/kubernetes
- https://rimzy.net/category/kubernetes-operator/
- https://nubenetes.com/kubernetes-tools/
- https://archive.sweetops.com/kubernetes/2020/05/
- https://www.devops.buzz/public/kubernetes/tools

**Comment by UtkarshShah0** [comment]
Sir, where is the shout-outs section or we have to create one in readme file?

**Comment by senthilrch** [comment]
The shout-outs section is in README file:-
https://github.com/senthilrch/kube-fledged/blob/develop/README.md

**Comment by senthilrch** [comment]
Raise PR against develop branch (not main branch)
