### ISSUE TITLE
Scale from zero node pool support?

### ISSUE THREAD

**Issue by phongcodelink** [senthilrch/kube-fledged#198]
Hello, thank you for the great repo. We plan to use this in our application however I have a few questions in mind.
- I have a ML application and 2 node pools one is CPU-only pool and one is GPU-pool that scale down to zero, can we do cache on CPU-only node then move this cache to GPU node when a new node appear?
- Where do `kube-fledged` store the image cache ? In the node disk, node memory or the persistent volume?

**Comment by senthilrch** [comment]
@phongcodelink:
- kube-fledged has an automatic cache refresh cycle. By default the cycle frequency is 15m. The frequency can be configured during deployment. Initially if the images are caches on the cpu-only nodes and later when a gpu node is added, the refresh cycle will automatically detect the newly added node and cache the images on those nodes.
- kube-fledged stores the image cache in the node's disk
