### ISSUE TITLE
Test kube-fledged in GKE and fix bugs

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#22]
kube-fledged is not yet tested in any cloud-native kubernetes services. It needs to be tested in Google Kubernetes Engine (GKE) using Google Container Registry (GCR). If any bugs are identified, these need to be fixed.

**Comment by sundeepk1** [comment]
Hi Senthil, i will take it up as I am trying to install kube-fledged on top of GKE

**Comment by senthilrch** [comment]
No update/response from @sundeepk1. Issue is stale for more than 30 days, so closing this issue.
