### ISSUE TITLE
New flag "--image-pull-policy" documentation

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#26]
### Configuration Flags

`--image-pull-deadline-duration:` Maximum duration allowed for pulling an image. After this duration, image pull is considered to have failed. default "5m"

`--image-cache-refresh-frequency:` The image cache is refreshed periodically to ensure the cache is up to date. Setting this flag to "0s" will disable refresh. default "15m"

`--docker-client-image:` The image name of the docker client. the docker client is used when deleting images during purging the cache".

**`--image-pull-policy:` Image pull policy for pulling images into the cache. Possible values are 'IfNotPresent' and 'Always'. Default value is 'IfNotPresent'. Default value for Images with ':latest' tag is 'Always'**

`--stderrthreshold:` Log level. set the value of this flag to INFO

## Description of new flag "--image-pull-policy" in cmd/fledged.go needs to be updated as follows:-

```go
flag.StringVar(&imagePullPolicy, "image-pull-policy", "", " Image pull policy for pulling images into the cache. Possible values are 'IfNotPresent' and 'Always'. Default value is 'IfNotPresent'. Default value for Images with ':latest' tag is 'Always'")
```

**Comment by sundeepk1** [comment]
Hi Senthil, 

I've updated the readme and cmd/fledged.go and created PR requests for them.

**Comment by senthilrch** [comment]
@sundeepk1 please update PR #28 with the changes requested.

**Comment by senthilrch** [comment]
PR #28 closed. Instead new PR #46 raised by @sundeepk1 .
PR #46 merged. Hence closing this issue.
