### ISSUE TITLE
swagger api documentation

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#5]
We will need to implement scripts to generate swagger spec and html api reference documents based on swagger spec. Refer following urls as e.g.:-

- https://github.com/kubernetes/kubernetes/blob/master/hack/update-generated-swagger-docs.sh
- https://github.com/kubernetes/kubernetes/blob/master/hack/update-swagger-spec.sh
- https://github.com/kubernetes/kubernetes/blob/master/hack/update-api-reference-docs.sh

**Comment by sundeepk1** [comment]
Hi Senthil,

Please assign this issue

**Comment by senthilrch** [comment]
@sundeepk1 : How is it going? we will need this for upcoming v0.1.3 release.

**Comment by senthilrch** [comment]
@sundeepk1 : kindly update the progress. can we get this done for v0.1.3 targetted for 30-Nov?

**Comment by senthilrch** [comment]
@kannanvr is working on this issue. Has raised PR #42.

**Comment by senthilrch** [comment]
No update from @kannanvr on PR #42, so closing this issue for now.
