### ISSUE TITLE
Allow kube-fledged to be deployed in any namespace

### ISSUE THREAD

**Issue by edshelton** [senthilrch/kube-fledged#52]
IMO hardcoding the namespace which the controller lives in is an antipattern:

https://github.com/senthilrch/kube-fledged/search?q=fledgedNameSpace&unscoped_q=fledgedNameSpace

Can this be changed so that `kube-fledged` can be deployed to any namespace?

```
E0224 13:17:38.339997       1 image_manager.go:442] Error creating job in node ip-10-0-30-82: namespaces "kube-fledged" not found
E0224 13:17:38.340905       1 image_manager.go:424] error pulling image 'golang:1.13' to node 'ip-10-0-30-82': namespaces "kube-fledged" not found
```

**Comment by senthilrch** [comment]
I'll have this changed to support deployment to any namespace. Will implement for v0.6.0
