### ISSUE TITLE
 Question: before setup kube-fledged use case

### ISSUE THREAD

**Issue by nandhyala** [senthilrch/kube-fledged#54]
@senthilrch @sundeepk1 ,

kube-fledged looks very good for pulling large images from diffrent zone for EKS autoscaling during peak hours. i have below question before going to setup kube-fledged in our eks clusters on our use-case.

1)We have image around 4 GB size  OF image and pulling from different region from  artifcatory taking more then 10 Mins and it is added autoscaling delays on cluster,If we use kube-fledged  it will solve our issue ?

2)If step 1 is yes then we are running only one container (4 GB )per node so how it will cache IMAGE on new  launched  server to avoid pulling image from artifcatory ? or it will pull from other running worker nodes ? could you please confirm ?

Thanks !

**Comment by senthilrch** [comment]
@nandhyala ,

1) Of course kube-fledged is built to solve the issue you have mentioned. kube-fledged is capable of pulling and caching images of any size. you can specify on to which worker nodes the image should be cached; you can choose to cache the image in all the worker nodes of the EKS cluster. 

2) when a new worker node is added to the cluster, if you have enabled auto-refresh, the image will get automatically pulled to the new node during the next refresh cycle. there is also an option to perform manual on-demand refresh. however it will be pulled from the image registry and not copied from a running worker node.

Hope this helps!

**Comment by nandhyala** [comment]
Thanks @senthilrch  for looking on my request, sorry I am still not clear on 2).That means whenever  new server launch it will go and pull images from artifcatory registry then how can we avoid delay issue in my case.Because my artifcatory registry is in different location cluster is different region.

**Comment by nandhyala** [comment]
correct me if i am wrong from (image registry) means from kube-fledged  cache image registry ? if yes how many images i can cache on image(size) registry  ,Just my curiosity where image cache  will storage in eks cluster ?

**Comment by senthilrch** [comment]
> Thanks @senthilrch for looking on my request, sorry I am still not clear on 2).That means whenever new server launch it will go and pull images from artifcatory registry then how can we avoid delay issue in my case.Because my artifcatory registry is in different location cluster is different region.

when a new server is launched, the image in the cache will be used to start the pod, provided the imagePullPolicy is set to IfNotPresent in the PodSpec. it will not be pulled from image registry

> correct me if i am wrong from (image registry) means from kube-fledged cache image registry ? if yes how many images (size )i can cache on registry ,Just my curiosity where image cache will storage in eks cluster ?

there is no limit to the number of images that can be cached. the images will be cached in the worker nodes of the eks cluster.

**Comment by nandhyala** [comment]
Thanks @senthilrch for details,I have successfully implemented  in our cluster using helm chart as per document. 

I have noticed below thing while pull image on new EC2 servers:
1) How we know new ec2 server is pulling docker image from image in the cache bcz the image path is same in application deployment & Image cache file ?
2) I noticed kube-fledged pod is pushing images into all servers ,How kube-fledged knows whenever new ec2 servers comes into Cluster ?
3) exactly kube-fledged pod will push images into all servers or new server will pull images from image cache ?
4)Using below files i have tested on one new EC2 launced server but i see not much performance on image pulling time compare to my orginal & image cache ,Both are took  same time around (3m54s ).

Could you please help me on above things if  it works  we will implement in our huge clusters(2000 Nodes -autoscaling eks cluster)

Below are log details.


**Image cache file entires:** 

apiVersion: fledged.k8s.io/v1alpha1
kind: ImageCache
metadata:
  name: imagecache2
  namespace: kube-fledged
spec:
  cacheSpec:
  - images:
    - artifactory.xxxxx.com/xxxxx-docker-snapshot-local/xxxxx_xxx_16:x.5-SNAPSHOT-1-985a252
  imagePullSecrets:
  - name: myregistrykey
********
**In application deployment:**

image: artifactory.xxxxx.com/xxxxx-docker-snapshot-local/xxxxx_xxx_16:x.5-SNAPSHOT-1-985a252
imagePullPolicy: **IfNotPresent**
*******
**Time took for pulling image on new server:**

 Normal   Scheduled         3m55s                  default-scheduler                                    Successfully assigned xxxxx-core-gpu/xxxx-gpu-xxxx-58bb5bdf77-c6dp9 to ip-1xx-xx-1x-xx.us-west-2.compute.internal
  Normal   Pulling           3m54s                  kubelet, ip-xxxxx.us-west-2.compute.internal  Pulling image "artifactory.xxxxx.com/xxxxx-docker-snapshot-local/xxxxx_xx_16:x.5-SNAPSHOT-1-985a252"
  Normal   Pulled            21s                    kubelet, ip-xxxxx.us-west-2.compute.internal  Successfully pulled image "artifactory.xxxxx.com/xxxxx-docker-snapshot-local/xxxxx_xx_16:x.5-SNAPSHOT-1-985a252"

********
Thanks ---

**Comment by senthilrch** [comment]
- after creating the imagecache, check the status field of the imagecache. ensure it shows a successful status. (please share the complete output of the imagecache object in json format)
- also verify if the image you mentioned in the imagecache object has been successfully pulled into the worker node (kubectl get node <nodename> -o json)
- make sure the application deployment is scaled only after the above two steps are completed.

**Comment by nandhyala** [comment]
Sure @senthilrch ,I will do once again and provide you log details,Here just i am trying to understand whenever new EC2 server comes up **first time** the docker will pull image from artifactory repo as per pod deployment file but in our case   pod deployment image will pull **first time** from artifactory repo **OR**  image cache from kube-fledged ? if its pull from image cache from local  it will helps  us on new launched ec2 machine otherwise if pull from  artifactory repo  it wont  help  much rite ?

**Comment by senthilrch** [comment]
of course, the image in the cache will be used, it will not be pulled from image registry. that's the whole purpose of kube-fledged.

**Comment by nandhyala** [comment]
Thanks @senthilrch confirmation its really helps us on our huge  size of images(4GB) pulling image from cache instead of artifactory repo on new launched ec2 machine,Is there anyway i can trigger only image pull from image cache whenever new servers is launched ? instead of doing entries refresh cache on EKS clusters because we have more than 1000+ servers dont want refresh again and again on old servers .

**Comment by nandhyala** [comment]
@senthilrch 

Today i have tested one more time and compared pulling image from image cache & artifactory repo.
Sorry to say i see not much performance with image cache pulling (3.5 GB ) image from image cache.

1) I have scheduled refresh cache frequency =10s on kubefledged to refresh cache every 10 sec on new launched nodes.

2) whenever launched new EC2 machine refresh cache picked new node started refresh as per below logs. It is took total 3M.27secs to complete sync job on new node (xxxx-gpu-package-z2-goldenqa-172.xx.xx.245)

3) To compare with pull from artifactory repo i have stoped refresh sync job on kubefledged &  logged into new server and removed image (artifactory.xxxxx.com/savant-docker-snapshot-local/xxxx_gpu_16:1.5-SNAPSHOT-1-985a252) manually .
4) On new server i went and executed doker pull artifactory.xxxx.com/xxxx-docker-snapshot-local/xxxx_gpu_16:1.5-SNAPSHOT-1-985a252 and pull is completed in 2M.34 secs ,Docker is completed more quicker then image cache pull job.Below is docker pull logs.

5) Can you please review logs and let me know if i am doing some thing wrong ? why it took more time for pulling image cache compare to artifactory ?

6) I think image puller (busybox) job is pulling image from artifactory repo only on new node not from image cache .

 

**Refesh sync kubefledged logfiles:**
****
I0412 04:49:08.572049       1 controller.go:438] Starting to sync image cache imagecachepkg01(refresh)
I0412 04:49:08.579649       1 controller.go:685] Completed sync actions for image cache imagecachepkg01(refresh)
I0412 04:49:08.595932       1 image_manager.go:413] Job imagecachepkg01-j2zpp created (pull:- artifactory.xxxxx.com/savant-docker-snapshot-local/xxxx_gpu_16:1.5-SNAPSHOT-1-985a252 --> savant-gpu-package-z2-goldenqa-172.xx.xx.245, runtime: docker://18.9.9)
I0412 04:52:35.345404       1 image_manager.go:173] Job imagecachepkg01-j2zpp succeeded (pull:- artifactory.xxxxx.com/savant-docker-snapshot-local/xxxx_gpu_16:1.5-SNAPSHOT-1-985a252 --> savant-gpu-package-z2-goldenqa-172.xx.xx.245, runtime: docker://18.9.9)
******

**Docker pull from artifactory repo logs:**

[root@xxxx-gpu-package-z2-goldenqa-172 ~]# date
Sun Apr 12 05:03:32 UTC 2020
[root@savant-gpu-package-z2-goldenqa-172 ~]# docker pull artifactory.xxxx.com/xxxx-docker-snapshot-local/xxxx_gpu_16:1.5-SNAPSHOT-1-985a252
1.5-SNAPSHOT-1-985a252: Pulling from xxxx-docker-snapshot-local/xxxx_gpu_16
976a760c94fc: Pull complete
c58992f3c37b: Pull complete
0ca0e5e7f12e: Pull complete
f2a274cc00ca: Pull complete
708a53113e13: Pull complete
42a5bd96796b: Pull complete
fa2cf2eae21c: Pull complete
0794b558dfd1: Pull complete
5c855def29e8: Pull complete
8fcc92b470b7: Pull complete
ca68f5a47b65: Pull complete
46457fac36a7: Pull complete
d7f2750401c2: Pull complete
f0c229bba94a: Pull complete
4c607f4ba40a: Pull complete
3800ccdf089f: Pull complete
406468ca5223: Pull complete
16675922831a: Pull complete
Digest: sha256:45ed6fa00fexxxx6ae92d6577d868e48e29612ca207de5b517374xxxx
Status: Downloaded newer image for artifactory.xxxx.com/xxxx-docker-snapshot-local/xxxx_gpu_16:1.5-SNAPSHOT-1-985a252
[root@xxxx-gpu-package-z2-goldenqa-172 ~]# date
Sun Apr 12 05:06:06 UTC 2020
[root@xxxx-gpu-package-z2-goldenqa-172 ~]#

**Busybox job pod describe :**

[ec2-user@ip-172-28-10-216 ~]$ kubectl describe pod imagecachepkg02-d7gvk-wzgjn -n kube-fledged
Name:               imagecachepkg02-d7gvk-wzgjn
Namespace:          kube-fledged
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=imagecache
# Please edit the object below. Lines beginning with a '#' will be ignored,
                    controller=fledged
                    controller-uid=4a7a408f-7ced-11ea-b1bd-025c2f3b0734
                    imagecache=imagecachepkg02
                    job-name=imagecachepkg02-d7gvk
Annotations:        kubernetes.io/psp: eks.privileged
Status:             Pending
IP:
Controlled By:      Job/imagecachepkg02-d7gvk
Init Containers:
  busybox:
    Image:      busybox:1.29.2
    Port:       <none>
    Host Port:  <none>
    Command:
      cp
      /bin/echo
      /tmp/bin
    Environment:  <none>
    Mounts:
      /tmp/bin from tmp-bin (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qccqk (ro)
Containers:
  imagepuller:
    Image:      artifactory.xxxx.com/xxxx-docker-snapshot-local/xxxxx_gpu_16:1.5-SNAPSHOT-1-985a252
    Port:       <none>
    Host Port:  <none>
    Command:

**Comment by senthilrch** [comment]
Yes, when a new worker node is added, for the first time, the image will be pulled from artifactory repo only. however during subsequent refresh cycles, the image will not be pulled from artifactory.

Are you expecting the image from existing EC2 node be copied to the new EC2 node instead of pulling it from artifactory? kube-fledged doesn't supports this.

**Comment by nandhyala** [comment]
Thanks @senthilrch ,Yes our challenge is whenever first time servers launch it pulls image from artifactory and taking time so i want pull somewhere from local at first time it self  instead of artifactory for new servers.

**Comment by senthilrch** [comment]
@nandhyala kube-fledged was never intended to solve the challenge you've mentioned. I request you to go through the list of use cases in README. for your problem, you can explore setting up mirror registries that are closer to your EC2 nodes (or) creating custom EC2 images with the container images baked in it. Thanks.

**Comment by mohammedi-haroune** [comment]
We are having the same challenges as @nandhyala, @senthilrch local/closer docker registry won't help because the pull time is bound by decompression not download.

Any suggestions? ideas?

**Comment by JarnoRFB** [comment]
Came here while looking at a similar use case: basically running training jobs on GPU nodes that should be scaled to zero for most of the day. The only solution that I have found, that does not require pulling images over the network on new worker nodes is [AKS scale down mode](https://docs.microsoft.com/en-us/azure/aks/scale-down-mode). This apparently allows you to reuse the worker node's disk including the images when scaling up again. Not sure if something similar exists for other cloud providers, but possibly one can implement something by oneself, by initializing new worker node disks from a snapshot.

**Comment by pat-s** [comment]
I was also hoping for this project to provide a shared image cache **during node startup** which prevents a subsequent pod to pull a (large) image again.

Unfortunately, this issue enlightened me that this is not possible.
Maybe it could be worth adding this piece of information somewhere into the README as more people might exactly search for this use case.

**Comment by agates4** [comment]
Adding to the comments here - I came to this repo hoping for this same use case. 
Starting new nodes without significant downtime is currently improbable without a shared image cache during node startup.
JarnoRFB's find about AKS is a compelling reason to use the Azure platform. I am investigating whether other platforms can provide the same functionality.
