### ISSUE TITLE
implement deletion of images in image cache

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#6]
when image cache resource is deleted (or) when image cache resource is modified by removing images, images already cached before in the worker nodes have to be deleted. fledged controller needs to take action to fire new jobs that would delete the image. this functionality needs to be implemented.

**Comment by senthilrch** [comment]
we will address only the deletion of imagecache resource in this issue. deleting images during imagecache update will be taken up in a separate issue.

**Comment by senthilrch** [comment]
We will implement imagecache deletion as follows:-

- Leverage Finalizers mechanism to have control over when the actual API resource get's deleted.
- As a pre-requisite, when the imagecache resource is created, fledged will add finalizer "fledged" to the resource.
- When user wants to delete the imagecache resource, it means the user's intention is to both delete the API resource + purge the cached images.
- User first needs to issue kubectl delete command with "--wait=false" option. Fledged controller will take actions to remove the cached images from the worker node. It will then update the status of the removal to status field of imagecache resource. However the finalizer "fledged" will not be removed yet, so the API resource will not be deleted yet.
- User then can query the imagecache resource using kubectl/curl to check the status of purging the imagecache. If there are any failures in removal, user should note down the image name and node and has to remove those failing images manually. Alternatively user can choose to leave the images in the worker nodes.
- User then needs to issue a second kubectl delete command with "--now". Fledged controller will remove the finalizer from the imagecache resource. The API resource will automatically get deleted. An event will also be generated.

**Comment by kannanv06** [comment]
@senthilrch , Kindly assign this issue to me

**Comment by senthilrch** [comment]
@kannanvr : How is it going?

**Comment by senthilrch** [comment]
@kannanvr : kindly update the progress if any
