### ISSUE TITLE
I am seeing Image pull failed and the message is "PodInitializing" under failure for every node. 

### ISSUE THREAD

**Issue by k8s-junkie** [senthilrch/kube-fledged#64]
I am trying to cache images that are 10+ GB on few nodes on my cluster. Any idea what this PodInitializing failure means?  
[centos@infra-vm ~]$ kubectl get imagecaches imagecache1 -n kube-fledged -o json
{
    "apiVersion": "kubefledged.k8s.io/v1alpha1",
    "kind": "ImageCache",
    "metadata": {
        "creationTimestamp": "2021-02-11T21:36:39Z",
        "generation": 3,
        "name": "imagecache1",
        "namespace": "kube-fledged",
        "resourceVersion": "1209980",
        "selfLink": "/apis/kubefledged.k8s.io/v1alpha1/namespaces/kube-fledged/imagecaches/imagecache1",
        "uid": "01386121-a9dd-4180-bd73-0163414a7515"
    },
    "spec": {
        "cacheSpec": [
            {
                "images": [
                    "nginx",
                    "tomcat:10.0.0"
                ]
            },
            {
                "images": [
                    "mec-docker.envrmnt.com/dreamscape/validator/mec-prometheus-server:latest"
                ],
                "nodeSelector": {
                    "slice-size": "ABOVE-6GB"
                }
            }
        ],
        "imagePullSecrets": [
            {
                "name": "jfrog"
            }
        ]
    },
    "status": {
        "completionTime": "2021-02-11T21:41:48Z",
        "failures": {
            "mec-docker.envrmnt.com/dreamscape/validator/mec-prometheus-server:latest": [
                {
                    "message": "",
                    "node": "hp-gpu-node3",
                    "reason": "PodInitializing"
                },
                {
                    "message": "",
                    "node": "hp-gpu-node2",
                    "reason": "PodInitializing"
                },
                {
                    "message": "",
                    "node": "hp-gpu-node0",
                    "reason": "PodInitializing"
                },
                {
                    "message": "",
                    "node": "hp-gpu-node6",
                    "reason": "PodInitializing"
                },
                {
                    "message": "",
                    "node": "hp-gpu-node7",
                    "reason": "PodInitializing"
                },
                {
                    "message": "",
                    "node": "hp-gpu-node4",
                    "reason": "PodInitializing"
                },
                {
                    "message": "",
                    "node": "hp-gpu-node5",
                    "reason": "PodInitializing"
                },
                {
                    "message": "",
                    "node": "hp-gpu-node1",
                    "reason": "PodInitializing"
                }
            ]
        },
        "message": "Image pull failed for some images. Please see \"failures\" section",
        "reason": "ImageCacheCreate",
        "startTime": "2021-02-11T21:36:39Z",
        "status": "Failed"
    }
}

**Comment by senthilrch** [comment]
@k8s-junkie : by default, the max. duration for pulling an image is 5 mins. For larger images increase the value:-

--image-pull-deadline-duration: Maximum duration allowed for pulling an image. After this duration, image pull is considered to have failed. default "5m"

**Comment by k8s-junkie** [comment]
@senthilrch Thx. Changing it to 30m fixed the issue.
