### ISSUE TITLE
Deployment using the Operator 0.8.0

### ISSUE THREAD

**Issue by zmarouf** [senthilrch/kube-fledged#75]
`make deploy-using-operator`  returns the following on EKS 1.20 flavor:

`The CertificateSigningRequest "kubefledged-webhook-server.kube-fledged" is invalid: spec.signerName: Invalid value: "kubernetes.io/legacy-unknown": the legacy signerName is not allowed via this API version`

**Comment by senthilrch** [comment]
@zmarouf : thanks for reporting this issue. can you try the following workaround:-

1. First uninstall: make remove-operator-and-kubefledged

2. In file deploy/webhook-create-signed-cert.sh, replace the following line
apiVersion=$(kubectl api-versions | grep certificates.k8s.io | head -1)

with:
apiVersion=certificates.k8s.io/v1beta1

3. Install again: 
make deploy-using-operator

**Comment by zmarouf** [comment]
Will do first thing in the morning and report back. Thanks for this!

**Comment by zmarouf** [comment]
`Error from server (InternalError): error when creating "deploy/kubefledged-imagecache.yaml": Internal error occurred: failed calling webhook "validate-image-cache.kubefledged.io": Post "https://kubefledged-webhook-server.kube-fledged.svc:3443/validate-image-cache?timeout=1s": service "kubefledged-webhook-server" not found`
I looked at the services and there's one named `kube-fledged-webhook-server` so I dumped that one and renamed it appropriately.

The verification call in the docs seems to also suffer from the same issue (kube-fledged vs kubefledged)
`kubectl get pods -n kube-fledged -l app.kubernetes.io/name=kubefledged # should be kube-fledged`

**Comment by senthilrch** [comment]
@zmarouf : thanks for sharing this. I'll fix this and publish new release.
I assume after you renamed the service name, you were able to create the image cache successfully?

**Comment by zmarouf** [comment]
Yes. It seems to have worked for me. Thanks for the workaround!

**Comment by lyonzy** [comment]
This happened to me too but I don't have `certificates.k8s.io/v1beta1` on my cluster so I had to figure out another approach. What worked was:

- Changing `signerName` to `kubernetes.io/kubelet-serving` (no idea whether this is correct or not)
- Changing the openssl `subj` arg to `/CN=system:node:${service}.${namespace}.svc;/O=system:nodes`
