### ISSUE TITLE
Incompatibility with carvel-kapp: object has been modified

### ISSUE THREAD

**Issue by universam1** [senthilrch/kube-fledged#77]
We are leveraging "vmware-tanzu/carvel-kapp" as our deployment tool.

When deploying the `refresh` annotation `kubefledged.k8s.io/refresh-imagecache` the action is failing in the `kube-fledged-controller` with following error:

```
kubefledged-controller-69dbc794d8-b2hg4 E0707 09:40:58.095098       1 controller.go:491] Error updating imagecache status to Processing: Operation cannot be fulfilled on imagecaches.kubefledged.io "my-image": the object has been modified; please apply your changes to the latest version and try again                                                                                                                  

kubefledged-controller-69dbc794d8-b2hg4 E0707 09:40:58.095124       1 controller.go:366] error syncing imagecache: Operation cannot be fulfilled on imagecaches.kubefledged.io "my-image": the object has been modified; please apply your changes to the latest version and try again
```

We highly believe the issue is related to a race condition, described more in detail here:

https://github.com/kubernetes/kubernetes/issues/67761

Workaround used within kapp:
https://github.com/vmware-tanzu/carvel-kapp/blob/d5b8c43b5678039c961b8369b2231860af9b5f90/pkg/kapp/resources/resources.go#L436-L438

**Comment by senthilrch** [comment]
@universam1: appreciate you posting this issue. I'll add a get ImageCache in
func (c *Controller) updateImageCacheStatus(imageCache *v1alpha2.ImageCache, status *v1alpha2.ImageCacheStatus)
before updating the status.
https://github.com/senthilrch/kube-fledged/blob/99993f7f8903609b3c40592f7c731680996c2027/cmd/controller/app/controller.go#L637

That should fix this issue.
