### ISSUE TITLE
Feature Request - Have a yaml only (no bash) way to deploy

### ISSUE THREAD

**Issue by vikas027** [senthilrch/kube-fledged#79]
At the moment, the installation requires running `make` targets which further calls some bash scripts to create certs.

While this works, the approach however is not GitOps friendly. It would be great if there is a way to install only using the yamls, be it standalone yaml(s) or a helm chart. Doing so, it will enable people to directly use yamls or helm charts in their GitOps repos (example Flux or ArgoCD)

**Comment by senthilrch** [comment]
@vikas027 : thanks for raising this. This is on the roadmap. first I need to sort out the generation of certificate for the webhook server. After CSR API has been updated to V1, it is not accepting "legacy-unknown" issuer. Other issuers are not generating the certificate with the expected "usage". I need to set aside sometime to look into this and sort out...

Will try to include this in upcoming v0.8.1

**Comment by vikas027** [comment]
Hey @senthilrch ,

Thanks for looking into this and updating the helm chart installation in the [documentation](https://github.com/senthilrch/kube-fledged/blob/master/README.md#quick-install-using-helm-chart). 

However, I can see these lines in the README. Does this means, I can only install the helm chart if I am on an Ubuntu machine? 
```bash
$ gpg --keyserver keyserver.ubuntu.com --recv-keys 92D793FA3A6460ED (or) gpg --keyserver pgp.mit.edu --recv-keys 92D793FA3A6460ED
$ gpg --export >~/.gnupg/pubring.gpg
```

**Comment by senthilrch** [comment]
Hi Vikas, no you can use any linux or mac box to run the helm installation.
helm charts of kube-fledged are signed using pgp, for improved security.
The pgp public key for verifying the signature is hosted in two different
public keyservers, you can use any one of them.

I've removed bash scripts. Now you can install the helm chart via gitops.

**Comment by vikas027** [comment]
Thanks, @senthilrch . I will give it a go soon.
