### ISSUE TITLE
Enhancement request: avoid hardcode busybox init container

### ISSUE THREAD

**Issue by brainfair** [senthilrch/kube-fledged#87]
Avoid hardcode image

https://github.com/senthilrch/kube-fledged/blob/163cd80c6e0020273da003fcdc2b62da701aa7e6/pkg/images/image_helpers.go#L87

Proposal:
Set image for busybox via Env or args like --cri-client-image

**Comment by senthilrch** [comment]
@brainfair : thanks for noticing this. I'll have this implemented in upcoming v0.8.1 release
