### ISSUE TITLE
generate events for every successful or failed sync and refresh action

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#9]
fledged controller needs to raise events for every successful or failed sync and refresh action, with appropriate human-readable message. these events could then be picked by other event processing tools for visibility and security.

**Comment by dreamer-89** [comment]
@senthilrch : Please assign this issue to me.

**Comment by senthilrch** [comment]
@dreamer-89 : thanks for you contribution. Please go ahead and work on this issue and raise a PR. All the best! I'll remove the help wanted label.

Note:- Event needs to be raised only after a successful status update to image cache.

**Comment by dreamer-89** [comment]
@senthilrch : Had a day off owing to Diwali in India. I am working on it now.

**Comment by dreamer-89** [comment]
Hi @senthilrch, i am getting below error when I try "make image" on terminal

> make image

> make: *** No rule to make target `image'.  Stop.

Please advise, how can i get rid of this error and proceed with docker set up on my local.

**Comment by senthilrch** [comment]
@dreamer-89 : you need to use "make fledged-image" instead of make image. I updated the master branch with changes to Makefile and README. Please refer to updated README for complete instructions.

https://github.com/senthilrch/kube-fledged/blob/master/README.md

**Comment by senthilrch** [comment]
@dreamer-89 : How is it going? If you need any help feel free to post your queries here. Am happy to help!

**Comment by senthilrch** [comment]
@dreamer-89 : How is it going? we will need this for upcoming v0.1.3 release.
