### ISSUE TITLE
Feature: Migrate kube-fledged ci to github actions

### ISSUE THREAD

**Issue by senthilrch** [senthilrch/kube-fledged#92]
Travis CI has announced EOL of their free offering for public repositories:-
https://travis-ci.org/github/senthilrch/kube-fledged

CI of kube-fledged need to be migrated to an alternate platform

**Comment by sundeepk1** [comment]
Can we consider Github actions for CI

**Comment by senthilrch** [comment]
SODACODE22: Raise PR against "develop" branch.
